
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lindo
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */int idpessoa;
     int tam;

    public int getTam() {
        return tam;
    }

    public void setTam(int size) {
        this.tam = size;
    }
     ArrayList<Produto> produ;
    public void setIdPessoa(int id){
        this.idpessoa=id;
    }
    public int getIdPessoa(){
        return idpessoa;
    }
    Conexao con;
    public TelaAdministrador() throws IOException, SQLException {
        initComponents();
        con=new Conexao();
        produ=new ArrayList<Produto>();
        produ=con.getProdutos();
        if(produ!=null){
            nome.setText(produ.get(0).getNome());
            descricao.setText(produ.get(0).getDescricao());
            precocusto.setText(Float.toString(produ.get(0).getPrecocusto()));
            precovenda.setText(Float.toString(produ.get(0).getPrecovenda()));
            foto.setIcon(produ.get(0).getFoto());
        }
        else{
            nome.setText("");
            descricao.setText("");
            precocusto.setText("");
            precovenda.setText("");
        }
        setTam(0);
        nprod.setText("PRODUTO: "+(getTam()+1));
    }
    public TelaAdministrador(int id) throws IOException, SQLException {
        initComponents();
        setIdPessoa(id);
        con=new Conexao();
        produ=new ArrayList<Produto>();
        produ=con.getProdutos();
        
        if(produ!=null){
            nome.setText(produ.get(0).getNome());
            descricao.setText(produ.get(0).getDescricao());
            precocusto.setText(Float.toString(produ.get(0).getPrecocusto()));
            precovenda.setText(Float.toString(produ.get(0).getPrecovenda()));
            foto.setIcon(produ.get(0).getFoto());
        }
        else{
            nome.setText("");
            descricao.setText("");
            precocusto.setText("");
            precovenda.setText("");
        }
        setTam(0);
        nprod.setText("PRODUTO: "+(getTam()+1));
    }
    
    

    public ArrayList<Produto> getProdu() {
        return produ;
    }

    public void setProdu(ArrayList<Produto> produ) {
        this.produ = produ;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adicionarproduto = new javax.swing.JButton();
        removerproduto = new javax.swing.JButton();
        alterarproduto = new javax.swing.JButton();
        home2 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();
        homei = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        precocusto = new javax.swing.JTextField();
        precovenda = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        ant = new javax.swing.JButton();
        prox = new javax.swing.JButton();
        slefoto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nprod = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel9.setText("jh.;k.jb;kK. J>VDV >>Dv /d,vvdvkd D >V D>vk .S vS");

        jLabel10.setText("..hvvvvvbbbbbbbbbbbbbbbh.kv..h.nbj.ub;/b;h,");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CONTA ADMINISTRADORA");

        adicionarproduto.setText("ADICIONAR ESTE PRODUTO COMO UM NOVO PRODUTO");
        adicionarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarprodutoActionPerformed(evt);
            }
        });

        removerproduto.setText("REMOVER ESTE PRODUTO");
        removerproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerprodutoActionPerformed(evt);
            }
        });

        alterarproduto.setText("ALTERAR ESTE PRODUTO");
        alterarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarprodutoActionPerformed(evt);
            }
        });

        home2.setText("voltar a home");
        home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home2MouseClicked(evt);
            }
        });

        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
        });

        homei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-página-inicial-24.png"))); // NOI18N
        homei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeiMouseClicked(evt);
            }
        });

        jLabel3.setText("NOME:");

        jLabel4.setText("CUSTO:");

        jLabel5.setText("PRECO DE VENDA:");

        jLabel6.setText("DESCRICAO:");

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        precocusto.setText(" ");
        precocusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precocustoActionPerformed(evt);
            }
        });

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/not-found.jpg"))); // NOI18N

        ant.setText("produto anterior");
        ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antActionPerformed(evt);
            }
        });

        prox.setText("proximo produto");
        prox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxActionPerformed(evt);
            }
        });

        slefoto.setText("selecionar outra imagem");
        slefoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slefotoActionPerformed(evt);
            }
        });

        jLabel7.setText("valores decimais sao separados por \".\"(ponto) EX: 99.9 ");

        jLabel8.setText("valores decimais sao separados por \".\"(ponto) EX: 99.9 ");

        nprod.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(65, 65, 65)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(nprod))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(homei, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(426, 426, 426)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(precovenda, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(precocusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(adicionarproduto)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alterarproduto)
                                    .addComponent(removerproduto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(ant)
                                .addGap(31, 31, 31)
                                .addComponent(prox)))))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slefoto)
                .addGap(467, 467, 467))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(home1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(homei))
                .addGap(6, 6, 6)
                .addComponent(home2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(precocusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(precovenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(slefoto)
                                .addGap(97, 97, 97))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(removerproduto)
                                .addGap(18, 18, 18)
                                .addComponent(alterarproduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionarproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ant)
                                    .addComponent(prox))
                                .addGap(26, 26, 26)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(nprod)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        //crie a tela principal passando novamente o parametro da chave primaria do usuario
    }//GEN-LAST:event_homeActionPerformed

    private void home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home2MouseClicked
        homeiMouseClicked(evt);
    }//GEN-LAST:event_home2MouseClicked

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        home1MouseClicked(evt);
    }//GEN-LAST:event_home1MouseClicked

    private void homeiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeiMouseClicked
        Home home = null;
         try {
             home = new Home(getIdPessoa());
         } catch (IOException ex) {
             Logger.getLogger(TelaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(TelaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
         }
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeiMouseClicked

    private void removerprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerprodutoActionPerformed
        if(produ.size()>0){
            int id=con.getIdProduto(nome.getText(), descricao.getText(), Float.parseFloat(precovenda.getText()));
            if(con.naoExistemPedidos(con.getIdProduto(nome.getText(), descricao.getText(), Float.parseFloat(precovenda.getText())))){
                con.removeCarrinho(con.getIdProduto(nome.getText(), descricao.getText(), Float.parseFloat(precovenda.getText())));
                con.removerProduto(nome.getText(),descricao.getText(),Float.parseFloat(precocusto.getText()),Float.parseFloat(precovenda.getText()));
                
                try {
                    produ=con.getProdutos();
                } catch (IOException ex) {
                    Logger.getLogger(TelaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                }
                       if(produ!=null){
                           nome.setText(produ.get(0).getNome());
                           descricao.setText(produ.get(0).getDescricao());
                           precocusto.setText(Float.toString(produ.get(0).getPrecocusto()));
                           precovenda.setText(Float.toString(produ.get(0).getPrecovenda()));
                           foto.setIcon(produ.get(0).getFoto());

                       }
                       else{
                           nome.setText("");
                           descricao.setText("");
                           precocusto.setText("");
                           precovenda.setText("");
                           foto.setIcon(null);
                       }
                       JOptionPane.showMessageDialog(null, "produto removido com sucesso");
                       setTam(0);
                       nprod.setText("PRODUTO: "+(getTam()+1));
            }else{
                JOptionPane.showMessageDialog(null,"EXISTEM PEDIDOS RELACIONADOS A ESTE PRODUTO, IMPOSSIVEL REMOVER");
            }
        }else{
            JOptionPane.showMessageDialog(null,"nao existem mais produtos para remover");
        }
            
    }//GEN-LAST:event_removerprodutoActionPerformed

    private void precocustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precocustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precocustoActionPerformed

    private void adicionarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarprodutoActionPerformed
        if(nome.getText().equals("")||descricao.getText().equals("")||precovenda.getText().equals("")||precocusto.getText().equals("")||con.getArquivo()==null){
            JOptionPane.showMessageDialog(null,"é preciso selecionar uma outra foto para o produto e nao podem haver campos em branco");
        }
        else{
            try{
                con.inserirProduto(nome.getText(), descricao.getText(), Float.parseFloat(precocusto.getText()), Float.parseFloat(precovenda.getText()));
                
                produ=con.getProdutos();
                if(produ!=null){
                    nome.setText(produ.get(0).getNome());
                    descricao.setText(produ.get(0).getDescricao());
                    precocusto.setText(Float.toString(produ.get(0).getPrecocusto()));
                    precovenda.setText(Float.toString(produ.get(0).getPrecovenda()));
                    foto.setIcon(produ.get(0).getFoto());
                }
                JOptionPane.showMessageDialog(null,"produto cadastrado com sucesso");
                setTam(0);
                nprod.setText("PRODUTO: "+(getTam()+1));
            }
            catch(Exception e){
                        JOptionPane.showMessageDialog(null,"os valores do custo ou do preco de venda nao estao de acordo com o pedido");
            }
        }
                    
    }//GEN-LAST:event_adicionarprodutoActionPerformed

    private void slefotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slefotoActionPerformed
        try {
            Image imagem=con.selectFoto();
            
            if(imagem!=null){
                foto.setIcon(new ImageIcon(imagem));
                
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "DESCULPE NAO FOI POSSIVEL SELECIONAR A FOTO, TENTE NOVAMENTE");
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_slefotoActionPerformed

    private void proxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxActionPerformed
         setTam(getTam()+1);
         if(produ!=null&&getTam()<=produ.size()-1){
             
             nome.setText(produ.get(getTam()).getNome());
             descricao.setText(produ.get(getTam()).getDescricao());
             precocusto.setText(Float.toString(produ.get(getTam()).getPrecocusto()));
             precovenda.setText(Float.toString(produ.get(getTam()).getPrecovenda()));
             foto.setIcon(produ.get(getTam()).getFoto());
             nprod.setText("PRODUTO: "+(getTam()+1));
         }else{
             setTam(getTam()-1);
             JOptionPane.showMessageDialog(null,"NAO TEM MAIS PRODUTOS");
         }
    }//GEN-LAST:event_proxActionPerformed

    private void antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antActionPerformed
       setTam(getTam()-1);
       if(getTam()>=0&&produ!=null){
           
           nome.setText(produ.get(getTam()).getNome());
           descricao.setText(produ.get(getTam()).getDescricao());
           precocusto.setText(Float.toString(produ.get(getTam()).getPrecocusto()));
           precovenda.setText(Float.toString(produ.get(getTam()).getPrecovenda()));
           foto.setIcon(produ.get(getTam()).getFoto());
           nprod.setText("PRODUTO: "+(getTam()+1));
       }else{
           setTam(getTam()+1);
           JOptionPane.showMessageDialog(null,"ESTE É O PRIMEIRO PRODUTO");
       }
    }//GEN-LAST:event_antActionPerformed

    private void alterarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarprodutoActionPerformed
        if(nome.getText().equals("")||descricao.getText().equals("")||precovenda.getText().equals("")||precocusto.getText().equals("")||con.getArquivo()==null){
            JOptionPane.showMessageDialog(null,"é preciso selecionar uma outra foto para o produto e nao podem haver campos em branco");
        }
        else{
        try {
             con.alteraProduto(nome.getText(),descricao.getText(),Float.parseFloat(precocusto.getText()),Float.parseFloat(precovenda.getText()),produ.get(getTam()));
             
             produ=con.getProdutos();
             if(produ!=null){
                nome.setText(produ.get(0).getNome());
                descricao.setText(produ.get(0).getDescricao());
                precocusto.setText(Float.toString(produ.get(0).getPrecocusto()));
                precovenda.setText(Float.toString(produ.get(0).getPrecovenda()));
                foto.setIcon(produ.get(0).getFoto());
            }
             JOptionPane.showMessageDialog(null,"produto alterado com sucesso");
             setTam(0);
             nprod.setText("PRODUTO: "+(getTam()+1));
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"os valores do custo ou do preco de venda nao estao de acordo com o pedido");
         } 
        }
    }//GEN-LAST:event_alterarprodutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new TelaAdministrador().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TelaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarproduto;
    private javax.swing.JButton alterarproduto;
    private javax.swing.JButton ant;
    private javax.swing.JTextArea descricao;
    private javax.swing.JLabel foto;
    private javax.swing.JButton home;
    private javax.swing.JLabel home1;
    private javax.swing.JLabel home2;
    private javax.swing.JLabel homei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nprod;
    private javax.swing.JTextField precocusto;
    private javax.swing.JTextField precovenda;
    private javax.swing.JButton prox;
    private javax.swing.JButton removerproduto;
    private javax.swing.JButton slefoto;
    // End of variables declaration//GEN-END:variables
}
